### ISSUE TITLE
payment succesfull is not loading

### ISSUE THREAD

**Issue by SureshKumar311** [sidharthasekhar129/paytm_gateway#1]
error ::  the web page is http://localhost:5000/server path /paymentReceipt could not be loaded because net::ERR_CONNECTION_REFUSED

but i had  change to in http://10.0.2.2:5000  due to android emulater has remapped but the payment was working but status is not  working  i am getting error 

plz help me 
thank you advance 
![Screenshot_1610460671](h
![Screenshot_1610460671](https://user-images.githubusercontent.com/51741195/104330820-665cd980-5514-11eb-9ca8-0560f819c5cf.png)
ttps://user-images.githubusercontent.com/51741195/104330729-45948400-5514-11eb-9958-4888478e06cc.png)

**Comment by SureshKumar311** [comment]
i found error in call back url  and i correct it

**Comment by sidharthasekhar129** [comment]
Hello Sureshkumar311,
  Glad you contacted me.I think there is a problem with ur callback url.
Send me your source file and i will have a look.
